version: '3.8'

services:
    mysqldb:
        ports:
          - 3307:3308
        image: mysql:latest
        environment:
        - MYSQL_ROOT_PASSWORD=1234
        volumes:
          - ./init:/docker-entrypoint-initdb.d
          - mysqlVolume:/var/lib/mysql
          - mysqlConfig:/etc/mysql
    docker-python:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
           - 3000:5000
        depends_on: 
          - mysqldb
volumes: 
    mysqlVolume: 
    mysqlConfig: 